
// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../../api/video/video_frame_buffer.h

package org.webrtc;

import androidx.annotation.IntDef;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@IntDef({
    VideoFrameBufferType.NATIVE, VideoFrameBufferType.I420, VideoFrameBufferType.I420A,
    VideoFrameBufferType.I422, VideoFrameBufferType.I444, VideoFrameBufferType.I010,
    VideoFrameBufferType.I210, VideoFrameBufferType.I410, VideoFrameBufferType.NV12
})
@Target(ElementType.TYPE_USE)
@Retention(RetentionPolicy.SOURCE)
public @interface VideoFrameBufferType {
  int NATIVE = 0;
  int I420 = 1;
  int I420A = 2;
  int I422 = 3;
  int I444 = 4;
  int I010 = 5;
  int I210 = 6;
  int I410 = 7;
  int NV12 = 8;
}
