//
// This file was generated by //third_party/jni_zero/jni_zero.py
//
package org.jni_zero;

import javax.annotation.processing.Generated;
import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniTestInstanceHolder;
import org.jni_zero.internal.NullUnmarked;
import org.jni_zero.internal.Nullable;

@CheckDiscard("crbug.com/993421")
@Generated("JNI Zero")
@SuppressWarnings({"rawtypes", "unchecked"})
@NullUnmarked
class JniZeroJni implements JniZero.Natives {
  private static @Nullable JniTestInstanceHolder sOverride;

  public static JniZero.Natives get() {
    JniTestInstanceHolder holder = sOverride;
    if (holder != null && holder.value != null) {
      return (JniZero.Natives) holder.value;
    }
    return new JniZeroJni();
  }

  public static void setInstanceForTesting(JniZero.Natives impl) {
    if (sOverride == null) {
      sOverride = JniTestInstanceHolder.create();
    }
    sOverride.value = impl;
  }


  @Override
  public void setJniClassLoader(ClassLoader classLoader) {
    GEN_JNI.org_jni_1zero_JniZero_setJniClassLoader(classLoader);
  }
}
